Varun/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view()),
    url(r'^app/', include( 'app.urls')),
]

app/urls.py
from django.conf.urls import url
from app import views

app_name = 'app'

urlpatterns = [
url(r'^$',views.TutorListView.as_view(), name = 'list')
]

app/models.py
from django.db import models
import uuid
# Create your models here.

class Tutor(models.Model):
    tutor_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tutor_first_name = models.CharField(max_length=128)
    tutor_last_name = models.CharField(max_length=128)
    tutor_email = models.EmailField(max_length=254, unique=True)
    tutor_booking_status = models.BooleanField()
    is_student = models.BooleanField()
    university_name = models.CharField(max_length=200)
    hourly_rate = models.DecimalField(max_digits=8, decimal_places=2)    #max_digits includes number of decimal places
    #tags = TaggableManager() #look at documentation https://pypi.python.org/pypi/django-taggit
    availability = models.BooleanField()
    tutor_intro = models.TextField()

    def __str__(self):
        return self.tutor_first_name

class Student(models.Model):
    #student_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    student_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    student_first_name = models.CharField(max_length=128)
    student_last_name = models.CharField(max_length=128)
    student_email = models.EmailField(max_length=254, unique=True)
    student_booking_status = models.BooleanField()
    is_tutor = models.BooleanField()
    tutor = models.ForeignKey(Tutor)


    def __str__(self):
        return self.student_first_name

app/views.py
from django.shortcuts import render
from django.views.generic import View,ListView,DetailView,TemplateView
# Create your views here.
from . import models

class IndexView(TemplateView):
    template_name = 'index.html'

class TutorListView(ListView):
    context_object_name = 'tutors'
    model = models.Tutor

class TutorDetailView(DetailView):
    context_object_name = 'tutor_details'
    model = models.Tutor
    template_name = 'app/tutor_detail.html'

app/templates/app/baseapp.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<title>base</title>
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'app:list' %}">Tutors</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="#"></a></li>
        </ul>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  {# Plugins#}

app/templates/app/tutor_detail.html
{% extends 'app/baseapp.html' %}
{% block body_block %}

<h1>Tutor Details</h1>
<p>{{tutor_details.tutor_last_name}}</p>
{% endblock %}

app/templates/app/tutor_list.html
{% extends "app/baseapp.html" %}

{% block body_block %}

<h1>List of Tutors</h1>
<ol>
  {% for tutor in tutors %}
  <h2><li>{{tutor.tutor_first_name}}</li></h2>
  {% endfor %}
</ol>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<title>base</title>
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'app:list' %}">Tutors</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="#"></a></li>
        </ul>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  {# Plugins#}

templates/index.html
{% extends "base.html" %}

  {% block body_block %}
  <h1>Home Page</h1>
  {% endblock %}